/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad06.graphics;

import actividad06.vehiculos.Camion;
import actividad06.vehiculos.Carga;
import actividad06.vehiculos.Coche;
import actividad06.vehiculos.IVehiculo;
import javax.swing.JTextField;

/**
 *
 * @author sergionicolaslopezgarcia
 */
public class DisplayAll extends javax.swing.JInternalFrame {

    /**
     * Creates new form DisplayAll
     */
    public DisplayAll() {
        initComponents();
        setTextFields();
        infoDisplayAll();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        typeDisplay1 = new javax.swing.JTextField();
        brandDisplay1 = new javax.swing.JTextField();
        modelDisplay1 = new javax.swing.JTextField();
        seatsDisplay1 = new javax.swing.JTextField();
        daysDisplay1 = new javax.swing.JTextField();
        gamaDisplay1 = new javax.swing.JTextField();
        weightDisplay1 = new javax.swing.JTextField();
        structureDisplay1 = new javax.swing.JTextField();
        priceDisplay1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        plateDisplay1 = new javax.swing.JTextField();
        typeDisplay2 = new javax.swing.JTextField();
        typeDisplay3 = new javax.swing.JTextField();
        typeDisplay4 = new javax.swing.JTextField();
        plateDisplay2 = new javax.swing.JTextField();
        plateDisplay3 = new javax.swing.JTextField();
        plateDisplay4 = new javax.swing.JTextField();
        brandDisplay2 = new javax.swing.JTextField();
        brandDisplay3 = new javax.swing.JTextField();
        brandDisplay4 = new javax.swing.JTextField();
        modelDisplay2 = new javax.swing.JTextField();
        modelDisplay3 = new javax.swing.JTextField();
        modelDisplay4 = new javax.swing.JTextField();
        seatsDisplay2 = new javax.swing.JTextField();
        seatsDisplay3 = new javax.swing.JTextField();
        seatsDisplay4 = new javax.swing.JTextField();
        daysDisplay2 = new javax.swing.JTextField();
        daysDisplay3 = new javax.swing.JTextField();
        daysDisplay4 = new javax.swing.JTextField();
        gamaDisplay2 = new javax.swing.JTextField();
        gamaDisplay3 = new javax.swing.JTextField();
        gamaDisplay4 = new javax.swing.JTextField();
        weightDisplay2 = new javax.swing.JTextField();
        weightDisplay3 = new javax.swing.JTextField();
        weightDisplay4 = new javax.swing.JTextField();
        structureDisplay2 = new javax.swing.JTextField();
        structureDisplay3 = new javax.swing.JTextField();
        structureDisplay4 = new javax.swing.JTextField();
        priceDisplay2 = new javax.swing.JTextField();
        priceDisplay3 = new javax.swing.JTextField();
        priceDisplay4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(17, 54, 74));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(199, 209, 214));
        jLabel1.setText("Datos del vehiculo");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(199, 209, 214));
        jLabel6.setText("Tipo:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(199, 209, 214));
        jLabel2.setText("Marca:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(199, 209, 214));
        jLabel3.setText("Modelo:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(199, 209, 214));
        jLabel4.setText("Asientos:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(199, 209, 214));
        jLabel5.setText("Dias alquiler:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(199, 209, 214));
        jLabel9.setText("Gama:");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(199, 209, 214));
        jLabel10.setText("Peso Max(Tn):");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(199, 209, 214));
        jLabel11.setText("Estructura:");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(199, 209, 214));
        jLabel12.setText("Precio(€):");

        typeDisplay1.setEditable(false);
        typeDisplay1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        typeDisplay1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        brandDisplay1.setEditable(false);
        brandDisplay1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        brandDisplay1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        modelDisplay1.setEditable(false);
        modelDisplay1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        modelDisplay1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seatsDisplay1.setEditable(false);
        seatsDisplay1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        seatsDisplay1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        daysDisplay1.setEditable(false);
        daysDisplay1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        daysDisplay1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gamaDisplay1.setEditable(false);
        gamaDisplay1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        gamaDisplay1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        weightDisplay1.setEditable(false);
        weightDisplay1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        weightDisplay1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        structureDisplay1.setEditable(false);
        structureDisplay1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        structureDisplay1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        priceDisplay1.setEditable(false);
        priceDisplay1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        priceDisplay1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(199, 209, 214));
        jLabel13.setText("Matrícula:");

        plateDisplay1.setEditable(false);
        plateDisplay1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        plateDisplay1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        typeDisplay2.setEditable(false);
        typeDisplay2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        typeDisplay2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        typeDisplay3.setEditable(false);
        typeDisplay3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        typeDisplay3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        typeDisplay4.setEditable(false);
        typeDisplay4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        typeDisplay4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        plateDisplay2.setEditable(false);
        plateDisplay2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        plateDisplay2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        plateDisplay3.setEditable(false);
        plateDisplay3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        plateDisplay3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        plateDisplay4.setEditable(false);
        plateDisplay4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        plateDisplay4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        brandDisplay2.setEditable(false);
        brandDisplay2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        brandDisplay2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        brandDisplay3.setEditable(false);
        brandDisplay3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        brandDisplay3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        brandDisplay4.setEditable(false);
        brandDisplay4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        brandDisplay4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        modelDisplay2.setEditable(false);
        modelDisplay2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        modelDisplay2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        modelDisplay3.setEditable(false);
        modelDisplay3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        modelDisplay3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        modelDisplay4.setEditable(false);
        modelDisplay4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        modelDisplay4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seatsDisplay2.setEditable(false);
        seatsDisplay2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        seatsDisplay2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seatsDisplay3.setEditable(false);
        seatsDisplay3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        seatsDisplay3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        seatsDisplay4.setEditable(false);
        seatsDisplay4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        seatsDisplay4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        daysDisplay2.setEditable(false);
        daysDisplay2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        daysDisplay2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        daysDisplay3.setEditable(false);
        daysDisplay3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        daysDisplay3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        daysDisplay4.setEditable(false);
        daysDisplay4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        daysDisplay4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gamaDisplay2.setEditable(false);
        gamaDisplay2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        gamaDisplay2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gamaDisplay3.setEditable(false);
        gamaDisplay3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        gamaDisplay3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gamaDisplay4.setEditable(false);
        gamaDisplay4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        gamaDisplay4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        weightDisplay2.setEditable(false);
        weightDisplay2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        weightDisplay2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        weightDisplay3.setEditable(false);
        weightDisplay3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        weightDisplay3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        weightDisplay4.setEditable(false);
        weightDisplay4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        weightDisplay4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        structureDisplay2.setEditable(false);
        structureDisplay2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        structureDisplay2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        structureDisplay3.setEditable(false);
        structureDisplay3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        structureDisplay3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        structureDisplay4.setEditable(false);
        structureDisplay4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        structureDisplay4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        priceDisplay2.setEditable(false);
        priceDisplay2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        priceDisplay2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        priceDisplay3.setEditable(false);
        priceDisplay3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        priceDisplay3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        priceDisplay4.setEditable(false);
        priceDisplay4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        priceDisplay4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(199, 209, 214));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Vehiculo 1");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(199, 209, 214));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Vehiculo 2");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(199, 209, 214));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Vehiculo 4");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(199, 209, 214));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Vehiculo 3");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(structureDisplay1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addComponent(weightDisplay1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(gamaDisplay1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(daysDisplay1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(seatsDisplay1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(modelDisplay1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(brandDisplay1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(plateDisplay1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(typeDisplay1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(priceDisplay1)))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(typeDisplay2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addComponent(plateDisplay2)
                        .addComponent(brandDisplay2)
                        .addComponent(modelDisplay2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(seatsDisplay2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(daysDisplay2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(gamaDisplay2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(weightDisplay2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(structureDisplay2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(priceDisplay2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(typeDisplay3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addComponent(plateDisplay3)
                        .addComponent(brandDisplay3)
                        .addComponent(modelDisplay3)
                        .addComponent(seatsDisplay3)
                        .addComponent(daysDisplay3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(gamaDisplay3)
                        .addComponent(weightDisplay3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(structureDisplay3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(priceDisplay3)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(typeDisplay4)
                    .addComponent(plateDisplay4)
                    .addComponent(brandDisplay4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modelDisplay4)
                    .addComponent(seatsDisplay4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(daysDisplay4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gamaDisplay4)
                    .addComponent(weightDisplay4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(structureDisplay4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(priceDisplay4))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(priceDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(priceDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(priceDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(priceDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(typeDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(plateDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plateDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plateDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plateDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(brandDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(modelDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(seatsDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatsDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatsDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatsDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(daysDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(daysDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(daysDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(daysDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(gamaDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gamaDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gamaDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gamaDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(weightDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(structureDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(structureDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(structureDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(structureDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setTextFields() {
        this.types[0] = this.typeDisplay1;
        this.types[1] = this.typeDisplay2;
        this.types[2] = this.typeDisplay3;
        this.types[3] = this.typeDisplay4;
        this.plates[0] = this.plateDisplay1;
        this.plates[1] = this.plateDisplay2;
        this.plates[2] = this.plateDisplay3;                
        this.plates[3] = this.plateDisplay4; 
        this.brands[0] = this.brandDisplay1;
        this.brands[1] = this.brandDisplay2;       
        this.brands[2] = this.brandDisplay3;        
        this.brands[3] = this.brandDisplay4;
        this.models[0] = this.modelDisplay1;
        this.models[1] = this.modelDisplay2;       
        this.models[2] = this.modelDisplay3;
        this.models[3] = this.modelDisplay4;
        this.seats[0] = this.seatsDisplay1;
        this.seats[1] = this.seatsDisplay2;        
        this.seats[2] = this.seatsDisplay3;        
        this.seats[3] = this.seatsDisplay4;
        this.days[0] = this.daysDisplay1;
        this.days[1] = this.daysDisplay2;
        this.days[2] = this.daysDisplay3;       
        this.days[3] = this.daysDisplay4;  
        this.gamas[0] = this.gamaDisplay1;
        this.gamas[1] = this.gamaDisplay2;
        this.gamas[2] = this.gamaDisplay3;
        this.gamas[3] = this.gamaDisplay4;
        this.prices[0] = this.priceDisplay1;
        this.prices[1] = this.priceDisplay2;   
        this.prices[2] = this.priceDisplay3;       
        this.prices[3] = this.priceDisplay4;
        this.weights[0] = this.weightDisplay1;
        this.weights[1] = this.weightDisplay2;
        this.weights[2] = this.weightDisplay3;       
        this.weights[3] = this.weightDisplay4;
        this.structures[0] = this.structureDisplay1;
        this.structures[1] = this.structureDisplay2;
        this.structures[2] = this.structureDisplay3;
        this.structures[3] = this.structureDisplay4;
    }
    
    public void infoDisplayAll() {
        for(int i = 1; i < actividad06.graphics.VehiculesMain.vehiculeList.length; i++) {
            IVehiculo toShow = actividad06.graphics.VehiculesMain.vehiculeList[i];
            if(toShow == null) {
                types[i-1].setText("");
                plates[i-1].setText("");
                brands[i-1].setText("");
                models[i-1].setText("");
                seats[i-1].setText("");
                days[i-1].setText("");
                gamas[i-1].setText("");
                prices[i-1].setText("");
                weights[i-1].setText("");
                structures[i-1].setText("");
            } else {
                switch (toShow.getClass().getSimpleName()) {
                case "Coche":
                    Coche car = (Coche) toShow;
                    types[i-1].setText("COCHE");
                    plates[i-1].setText(car.getLicense().toUpperCase());
                    brands[i-1].setText(car.getBrand().toUpperCase());
                    models[i-1].setText(car.getModel().toUpperCase());
                    seats[i-1].setText(Integer.toString(car.getNumSeats()));
                    days[i-1].setText(Integer.toString(car.getNumberDaysRented()));
                    gamas[i-1].setText(car.getGama().toString());
                    prices[i-1].setText(Double.toString(car.getTotalPriceOfRent()));
                    weights[i-1].setText("");
                    structures[i-1].setText("");
                    break;
                case "Carga":
                    Carga carga = (Carga) toShow;
                    types[i-1].setText("CARGA");
                    plates[i-1].setText(carga.getLicense().toUpperCase());
                    brands[i-1].setText(carga.getBrand().toUpperCase());
                    models[i-1].setText(carga.getModel().toUpperCase());
                    seats[i-1].setText(Integer.toString(carga.getNumSeats()));
                    days[i-1].setText(Integer.toString(carga.getNumberDaysRented()));
                    gamas[i-1].setText("");
                    prices[i-1].setText(Double.toString(carga.getTotalPriceOfRent()));
                    weights[i-1].setText(Double.toString(carga.getPMA()));
                    structures[i-1].setText("");
                    break;
                case "Camion":
                    Camion truck = (Camion) toShow;
                    types[i-1].setText("CAMION");
                    plates[i-1].setText(truck.getLicense().toUpperCase());
                    brands[i-1].setText(truck.getBrand().toUpperCase());
                    models[i-1].setText(truck.getModel().toUpperCase());
                    seats[i-1].setText(Integer.toString(truck.getNumSeats()));
                    days[i-1].setText(Integer.toString(truck.getNumberDaysRented()));
                    gamas[i-1].setText("");
                    prices[i-1].setText(Double.toString(truck.getTotalPriceOfRent()));
                    weights[i-1].setText(Double.toString(truck.getPMA()));
                    structures[i-1].setText(truck.getStructure().toString());
                    break;
                }
            }
        }
    }
    
    private JTextField[] types = new JTextField[4];
    private JTextField[] plates = new JTextField[4];
    private JTextField[] brands = new JTextField[4];
    private JTextField[] models = new JTextField[4];
    private JTextField[] seats = new JTextField[4];
    private JTextField[] days = new JTextField[4];
    private JTextField[] gamas = new JTextField[4];
    private JTextField[] weights = new JTextField[4];
    private JTextField[] structures = new JTextField[4];
    private JTextField[] prices = new JTextField[4];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandDisplay1;
    private javax.swing.JTextField brandDisplay2;
    private javax.swing.JTextField brandDisplay3;
    private javax.swing.JTextField brandDisplay4;
    private javax.swing.JTextField daysDisplay1;
    private javax.swing.JTextField daysDisplay2;
    private javax.swing.JTextField daysDisplay3;
    private javax.swing.JTextField daysDisplay4;
    private javax.swing.JTextField gamaDisplay1;
    private javax.swing.JTextField gamaDisplay2;
    private javax.swing.JTextField gamaDisplay3;
    private javax.swing.JTextField gamaDisplay4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField modelDisplay1;
    private javax.swing.JTextField modelDisplay2;
    private javax.swing.JTextField modelDisplay3;
    private javax.swing.JTextField modelDisplay4;
    private javax.swing.JTextField plateDisplay1;
    private javax.swing.JTextField plateDisplay2;
    private javax.swing.JTextField plateDisplay3;
    private javax.swing.JTextField plateDisplay4;
    private javax.swing.JTextField priceDisplay1;
    private javax.swing.JTextField priceDisplay2;
    private javax.swing.JTextField priceDisplay3;
    private javax.swing.JTextField priceDisplay4;
    private javax.swing.JTextField seatsDisplay1;
    private javax.swing.JTextField seatsDisplay2;
    private javax.swing.JTextField seatsDisplay3;
    private javax.swing.JTextField seatsDisplay4;
    private javax.swing.JTextField structureDisplay1;
    private javax.swing.JTextField structureDisplay2;
    private javax.swing.JTextField structureDisplay3;
    private javax.swing.JTextField structureDisplay4;
    private javax.swing.JTextField typeDisplay1;
    private javax.swing.JTextField typeDisplay2;
    private javax.swing.JTextField typeDisplay3;
    private javax.swing.JTextField typeDisplay4;
    private javax.swing.JTextField weightDisplay1;
    private javax.swing.JTextField weightDisplay2;
    private javax.swing.JTextField weightDisplay3;
    private javax.swing.JTextField weightDisplay4;
    // End of variables declaration//GEN-END:variables
}
