
package actividad06.graphics;

import actividad06.vehiculos.Camion;
import actividad06.vehiculos.Carga;
import actividad06.vehiculos.Coche;
import actividad06.vehiculos.Vehiculo;
import actividad06.vehiculos.VehiculoVerifications;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author sergionicolaslopezgarcia
 */
public class InfoDisplay extends javax.swing.JInternalFrame {

    /**
     * Creates new form infoDisplay
     * @param spots The array of JLabels of the desktop, where the icons of vehicules are added
     */
    public InfoDisplay(JLabel[] spots) {
        initComponents();
        this.spots = spots;
        this.setMinimumSize(new Dimension(700, 700));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        introduceButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        positionComboBox = new javax.swing.JComboBox<>();
        modelDisplay = new javax.swing.JTextField();
        brandDisplay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        seatsDisplay = new javax.swing.JTextField();
        typeDisplay = new javax.swing.JTextField();
        weightDisplay = new javax.swing.JTextField();
        priceDisplay = new javax.swing.JTextField();
        gamaDisplay = new javax.swing.JTextField();
        daysDisplay = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        structureDisplay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        plateDisplay = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(17, 54, 74));

        introduceButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        introduceButton.setText("Introducir");
        introduceButton.setEnabled(false);
        introduceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introduceButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(199, 209, 214));
        jLabel1.setText("Info del nuevo vehículo");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(199, 209, 214));
        jLabel11.setText("Precio(€):");

        positionComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        positionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Posición 1", "Posición 2", "Posición 3", "Posición 4" }));
        positionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionComboBoxActionPerformed(evt);
            }
        });

        modelDisplay.setEditable(false);
        modelDisplay.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        modelDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        brandDisplay.setEditable(false);
        brandDisplay.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        brandDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(199, 209, 214));
        jLabel3.setText("Modelo:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(199, 209, 214));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("En qué posición lo quieres almacenar?");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(199, 209, 214));
        jLabel6.setText("Tipo:");

        seatsDisplay.setEditable(false);
        seatsDisplay.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        seatsDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        typeDisplay.setEditable(false);
        typeDisplay.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        typeDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        weightDisplay.setEditable(false);
        weightDisplay.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        weightDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        priceDisplay.setEditable(false);
        priceDisplay.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        priceDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gamaDisplay.setEditable(false);
        gamaDisplay.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        gamaDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        daysDisplay.setEditable(false);
        daysDisplay.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        daysDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(199, 209, 214));
        jLabel8.setText("Gama:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(199, 209, 214));
        jLabel5.setText("Dias alquiler:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(199, 209, 214));
        jLabel9.setText("Peso Max(Tn):");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(199, 209, 214));
        jLabel4.setText("Asientos:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(199, 209, 214));
        jLabel2.setText("Marca:");

        structureDisplay.setEditable(false);
        structureDisplay.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        structureDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(199, 209, 214));
        jLabel10.setText("Estructura:");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(199, 209, 214));
        jLabel12.setText("Matrícula:");

        plateDisplay.setEditable(false);
        plateDisplay.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        plateDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel6))
                            .addGap(48, 48, 48)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(typeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(plateDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(48, 48, 48)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(weightDisplay)
                                .addComponent(priceDisplay)
                                .addComponent(gamaDisplay)
                                .addComponent(daysDisplay)
                                .addComponent(modelDisplay)
                                .addComponent(seatsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(structureDisplay)
                                .addComponent(brandDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(positionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(introduceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(34, 34, 34)
                .addComponent(positionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(typeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(plateDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(brandDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(modelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(seatsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(daysDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(gamaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(weightDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(structureDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(priceDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(introduceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void positionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionComboBoxActionPerformed
        introduceButton.setEnabled(true);
        introduceButton.requestFocus();
    }//GEN-LAST:event_positionComboBoxActionPerformed
    
    /**
     * Method to complete all the TextFields with the Vehicule info
     * @param vehicule The vehicule to get the info from
     */
    public void completeVehiculeInfo(Vehiculo vehicule) {
        switch (vehicule.getClass().getSimpleName()) {//Get the name of the vehicule's class
            case "Coche":
                Coche car = (Coche) vehicule;
                typeDisplay.setText("COCHE");
                plateDisplay.setText(car.getLicense().toUpperCase());
                brandDisplay.setText(car.getBrand().toUpperCase());
                modelDisplay.setText(car.getModel().toUpperCase());
                seatsDisplay.setText(Integer.toString(car.getNumSeats()));
                daysDisplay.setText(Integer.toString(car.getNumberDaysRented()));
                gamaDisplay.setText(car.getGama().toString());
                priceDisplay.setText(Double.toString(car.getTotalPriceOfRent()));
                actividad06.graphics.VehiculesMain.vehiculeList[positionComboBox.getSelectedIndex()] = car;
                break;
            case "Carga":
                Carga carga = (Carga) vehicule;
                typeDisplay.setText("CARGA");
                plateDisplay.setText(carga.getLicense().toUpperCase());
                brandDisplay.setText(carga.getBrand().toUpperCase());
                modelDisplay.setText(carga.getModel().toUpperCase());
                seatsDisplay.setText(Integer.toString(carga.getNumSeats()));
                daysDisplay.setText(Integer.toString(carga.getNumberDaysRented()));
                weightDisplay.setText(Double.toString(carga.getPMA()));
                priceDisplay.setText(Double.toString(carga.getTotalPriceOfRent()));
                actividad06.graphics.VehiculesMain.vehiculeList[positionComboBox.getSelectedIndex()] = carga;
                break;
            case "Camion":
                Camion truck = (Camion) vehicule;
                typeDisplay.setText("CAMION");
                plateDisplay.setText(truck.getLicense().toUpperCase());
                brandDisplay.setText(truck.getBrand().toUpperCase());
                modelDisplay.setText(truck.getModel().toUpperCase());
                seatsDisplay.setText(Integer.toString(truck.getNumSeats()));
                daysDisplay.setText(Integer.toString(truck.getNumberDaysRented()));
                weightDisplay.setText(Double.toString(truck.getPMA()));
                priceDisplay.setText(Double.toString(truck.getTotalPriceOfRent()));
                structureDisplay.setText(truck.getStructure().toString());
                actividad06.graphics.VehiculesMain.vehiculeList[positionComboBox.getSelectedIndex()] = truck;
                break;
        }
    }
    
    /**
     * Method to add the vehicule images to the "parking spots"
     * @param spots the array of JLabels where the images will be added
     */
    public void spotDisplay(JLabel[] spots) {
        for(int i = 1; i < actividad06.graphics.VehiculesMain.vehiculeList.length; i++) {
                if(actividad06.graphics.VehiculesMain.vehiculeList[i] == null) {
                    spots[i-1].setIcon(null);// The icon is set to null if there is no vehicule in that spot
                } else {
                    switch (actividad06.graphics.VehiculesMain.vehiculeList[i].getClass().getSimpleName()) {
                    case "Coche":
                        spots[i-1].setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad06/graphics/files/car.png")));
                        break;
                    case "Carga":
                        spots[i-1].setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad06/graphics/files/carga.png")));
                        break;
                    case "Camion":
                        spots[i-1].setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad06/graphics/files/truck.png")));
                        break;
                    }
                }
        }
        if(VehiculoVerifications.parkingFull()) {//If the parking is full, changed the parking sign for a "Parking Complete Sign"
            spots[4].setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad06/graphics/Images copia 4/parkingComplete.png")));
        }
    }
    
    /**
     * Method when introduce button is clicked. Add the vehicule to the Ivehiculo array
     */
    private int introduceButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int overW = 0;
        if(actividad06.graphics.VehiculesMain.vehiculeList[positionComboBox.getSelectedIndex() + 1] != null) {
            overW = JOptionPane.showConfirmDialog(null, "¿Esta seguro que deseas sobreescribirlo?", "Hay un vehiculo en esa posición!", JOptionPane.YES_NO_OPTION);
            if(overW == 1) {
                positionComboBox.requestFocus();
                return -1;
            } else {
                actividad06.graphics.VehiculesMain.vehiculeList[positionComboBox.getSelectedIndex() + 1] = actividad06.graphics.VehiculesMain.vehiculeList[0];
                actividad06.graphics.VehiculesMain.vehiculeList[0] = null;
            }
        } else {
            actividad06.graphics.VehiculesMain.vehiculeList[positionComboBox.getSelectedIndex() + 1] = actividad06.graphics.VehiculesMain.vehiculeList[0];
            actividad06.graphics.VehiculesMain.vehiculeList[0] = null;
        }
        
        spotDisplay(spots);
        JOptionPane.showMessageDialog(null, "Has creado e introducido exitosamente el nuevo vehiculo!");
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            JOptionPane.showMessageDialog(null, "Ha habido un error al intentar cerrar!", "Error!", JOptionPane.WARNING_MESSAGE);
        } 
        
        return overW;
    }
    
/*    
    private void introduceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introduceButtonActionPerformed
    }//GEN-LAST:event_introduceButtonActionPerformed
*/    
    private JLabel[] spots;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandDisplay;
    private javax.swing.JTextField daysDisplay;
    private javax.swing.JTextField gamaDisplay;
    private javax.swing.JButton introduceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField modelDisplay;
    private javax.swing.JTextField plateDisplay;
    private javax.swing.JComboBox<String> positionComboBox;
    private javax.swing.JTextField priceDisplay;
    private javax.swing.JTextField seatsDisplay;
    private javax.swing.JTextField structureDisplay;
    private javax.swing.JTextField typeDisplay;
    private javax.swing.JTextField weightDisplay;
    // End of variables declaration//GEN-END:variables
}
